DELETE
FROM bookings;
DELETE
FROM comments;
DELETE
FROM items;
DELETE
FROM requests;
DELETE
FROM users;
ALTER TABLE users
    ALTER COLUMN id RESTART;
ALTER TABLE items
    ALTER COLUMN id RESTART;
ALTER TABLE requests
    ALTER COLUMN id RESTART;
ALTER TABLE bookings
    ALTER COLUMN id RESTART;
ALTER TABLE comments
    ALTER COLUMN id RESTART;